owner: HT2-Labs
repo: upptime-status

sites:
- name: Jenkins
  url: $JENKINS_SITE
- name: dev
  url: $DEV_SITE
- name: UAT
  url: $UAT_SITE
- name: prod
  url: $PROD_SITE
- name: Stream LXP
  url: $STREAM_SITE
- name: Stream LXP US
  url: $STREAM_US_SITE
- name: Learning Locker
  url: $LL_SITE
- name: Learning Locker US
  url: $LL_US_SITE
- name: Waves
  url: $WAVES_SITE
assignees:
  - AodhanLP

status-website:
  baseUrl: /upptime-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: dark
  name: Upptime Status
  introTitle: "**Upptime Status**"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/HT2-Labs/upptime-status) to track Learning Pool sites including our Jenkins server, Stream, Learning Locker, and Waves sites.
  navbar:
    - title: Status
      href: /upptime-status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
